apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f odkcentral.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pyxform
  name: pyxform
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyxform
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f odkcentral.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pyxform
    spec:
      containers:
      - image: getodk/pyxform-http:v1.0.0
        imagePullPolicy: ""
        name: pyxform
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
