apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f odkcentral.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: secrets
  name: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secrets
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f odkcentral.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: secrets
    spec:
      containers:
      - args:
        - ./generate-secrets.sh
        image: ghcr.io/dbca-wa/odk-secrets:latest
        imagePullPolicy: ""
        name: secrets
        resources: {}
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: secrets
        persistentVolumeClaim:
          claimName: secrets
status: {}
