version: "3"
services:

  postgres:
    image: "postgres:9.6"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DATABASE: odk
    restart: always

  mail:
    container_name: mail
    image: "ghcr.io/dbca-wa/odk-mail:latest"
    environment:
      - MAILNAME=${DOMAIN}
    restart: always

  service:
    container_name: service
    image: "ghcr.io/dbca-wa/odk-service:latest"
    depends_on:
      - secrets
      - postgres
      - mail
      - pyxform
      - enketo
    volumes:
      - secrets:/etc/secrets
      - /data/transfer:/data/transfer
    environment:
      - DOMAIN=${DOMAIN}
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]
    restart: always

  nginx:
    container_name: nginx
    image: "ghcr.io/dbca-wa/odk-nginx:latest"
    depends_on:
      - service
      - enketo
    environment:
      - SSL_TYPE=${SSL_TYPE}
      - DOMAIN=${DOMAIN}
      - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 443 || exit 1" ]
    restart: always

  pyxform:
    container_name: pyxform
    image: 'getodk/pyxform-http:v1.0.0'
    restart: always

  secrets:
    image: "ghcr.io/dbca-wa/odk-secrets:latest"
    container_name: secrets
    volumes:
      - secrets:/etc/secrets
    command: './generate-secrets.sh'

  enketo:
    image: "ghcr.io/dbca-wa/odk-enketo:latest"
    container_name: enketo
    volumes:
      - secrets:/etc/secrets
    restart: always
    depends_on:
      - secrets
      - enketo_redis_main
      - enketo_redis_cache
    environment:
      - DOMAIN=${DOMAIN}
      - SUPPORT_EMAIL=${SYSADMIN_EMAIL}

  enketo_redis_main:
    image: "ghcr.io/dbca-wa/odk-enketo-redis-main:latest"
    container_name: enketo_redis_main
    volumes:
      - enketo_redis_main:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always

  enketo_redis_cache:
    image: "ghcr.io/dbca-wa/odk-enketo-redis-cache:latest"
    container_name: enketo_redis_cache
    volumes:
      - enketo_redis_cache:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always

volumes:
  transfer:
  enketo_redis_main:
  enketo_redis_cache:
  secrets:


